<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:actormapping="http://www.bonitasoft.org/ns/actormapping/6.0" xmlns:configuration="http://www.bonitasoft.org/ns/bpm/configuration" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:parameter="http://www.bonitasoft.org/ns/bpm/parameter" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_rY-CwDz9Ee6gLs_iytuHkw" name="_sampleProcessWithParameter" bonitaModelVersion="9">
    <elements xmi:type="process:Pool" xmi:id="_rY-CwTz9Ee6gLs_iytuHkw" name="_processWithParameter">
      <elements xmi:type="process:Lane" xmi:id="_rY-Cwjz9Ee6gLs_iytuHkw" name="Employee lane" actor="_rY-p0jz9Ee6gLs_iytuHkw">
        <elements xmi:type="process:StartEvent" xmi:id="_rY-Cwzz9Ee6gLs_iytuHkw" name="Start1" outgoing="_xitBIDz9Ee6gLs_iytuHkw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_rY-CxDz9Ee6gLs_iytuHkw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_rY-CxTz9Ee6gLs_iytuHkw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_rY-Cxjz9Ee6gLs_iytuHkw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_xilsYDz9Ee6gLs_iytuHkw" name="End1" incoming="_xitBIDz9Ee6gLs_iytuHkw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ximTcTz9Ee6gLs_iytuHkw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ximTcDz9Ee6gLs_iytuHkw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ximTcjz9Ee6gLs_iytuHkw" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_rY-C1Dz9Ee6gLs_iytuHkw" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_B_KzkDz-Ee6eiMvMiMEZEg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_rY-C1jz9Ee6gLs_iytuHkw">
        <targetForm xmi:type="expression:Expression" xmi:id="_rY-C1zz9Ee6gLs_iytuHkw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xitBIDz9Ee6gLs_iytuHkw" target="_xilsYDz9Ee6gLs_iytuHkw" source="_rY-Cwzz9Ee6gLs_iytuHkw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xitBITz9Ee6gLs_iytuHkw"/>
        <condition xmi:type="expression:Expression" xmi:id="_xitBIjz9Ee6gLs_iytuHkw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_rY-p0jz9Ee6gLs_iytuHkw" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <configurations xmi:type="configuration:Configuration" xmi:id="_-bc1MDz9Ee6eiMvMiMEZEg" name="Qualification" version="9" username="walter.bates">
        <actorMappings xmi:type="actormapping:ActorMappingsType" xmi:id="_-beDVzz9Ee6eiMvMiMEZEg">
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_-beDWDz9Ee6eiMvMiMEZEg" name="Employee actor">
            <groups xmi:type="actormapping:Groups" xmi:id="_-beDWTz9Ee6eiMvMiMEZEg"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_-beDWjz9Ee6eiMvMiMEZEg"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_-beDWzz9Ee6eiMvMiMEZEg">
              <role>member</role>
            </roles>
            <users xmi:type="actormapping:Users" xmi:id="_-beDXDz9Ee6eiMvMiMEZEg"/>
          </actorMapping>
        </actorMappings>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_-bc1MTz9Ee6eiMvMiMEZEg" id="CONNECTOR"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_-bc1Mzz9Ee6eiMvMiMEZEg" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_-bc1NDz9Ee6eiMvMiMEZEg" id="OTHER"/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_-beDXTz9Ee6eiMvMiMEZEg" name="sampleParameter" value="testValue" typeClassname="java.lang.String"/>
      </configurations>
      <configurations xmi:type="configuration:Configuration" xmi:id="_UYjYkBN8Ee-sFtxxgBEFKw" name="presales" version="9" username="walter.bates">
        <actorMappings xmi:type="actormapping:ActorMappingsType" xmi:id="_UYj_oBN8Ee-sFtxxgBEFKw">
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_UYj_oRN8Ee-sFtxxgBEFKw" name="Employee actor">
            <groups xmi:type="actormapping:Groups" xmi:id="_UYj_ohN8Ee-sFtxxgBEFKw"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_UYj_oxN8Ee-sFtxxgBEFKw"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_UYj_pBN8Ee-sFtxxgBEFKw">
              <role>member</role>
            </roles>
            <users xmi:type="actormapping:Users" xmi:id="_UYj_pRN8Ee-sFtxxgBEFKw"/>
          </actorMapping>
        </actorMappings>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_UYj_phN8Ee-sFtxxgBEFKw" id="CONNECTOR"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_UYj_rBN8Ee-sFtxxgBEFKw" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_UYj_rRN8Ee-sFtxxgBEFKw" id="OTHER"/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_UYj_sxN8Ee-sFtxxgBEFKw" name="sampleParameter" value="testValue" typeClassname="java.lang.String"/>
      </configurations>
      <parameters xmi:type="parameter:Parameter" xmi:id="_8AP-EDz9Ee6eiMvMiMEZEg" name="sampleParameter" typeClassname="java.lang.String"/>
      <contract xmi:type="process:Contract" xmi:id="_rY-p0zz9Ee6gLs_iytuHkw"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_rY-p1Dz9Ee6gLs_iytuHkw">
        <name xmi:type="expression:Expression" xmi:id="_rY-p1Tz9Ee6gLs_iytuHkw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_rY-p1jz9Ee6gLs_iytuHkw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_rY-p1zz9Ee6gLs_iytuHkw">
        <name xmi:type="expression:Expression" xmi:id="_rY-p2Dz9Ee6gLs_iytuHkw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_rY-p2Tz9Ee6gLs_iytuHkw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_rY-p2jz9Ee6gLs_iytuHkw">
        <name xmi:type="expression:Expression" xmi:id="_rY-p2zz9Ee6gLs_iytuHkw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_rY-p3Dz9Ee6gLs_iytuHkw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_rY-p3Tz9Ee6gLs_iytuHkw">
        <name xmi:type="expression:Expression" xmi:id="_rY-p3jz9Ee6gLs_iytuHkw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_rY-p3zz9Ee6gLs_iytuHkw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_rY-p4Dz9Ee6gLs_iytuHkw">
        <name xmi:type="expression:Expression" xmi:id="_rY-p4Tz9Ee6gLs_iytuHkw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_rY-p4jz9Ee6gLs_iytuHkw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_w7zEcKPPEe6PUdC4JjCMCw" name="_processWithServerUrlParam">
      <elements xmi:type="process:StartEvent" xmi:id="_0tplcKPPEe6PUdC4JjCMCw" name="Start2" outgoing="_1OBuoKPPEe6PUdC4JjCMCw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_0tvFAKPPEe6PUdC4JjCMCw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_0tud8KPPEe6PUdC4JjCMCw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_0tvFAaPPEe6PUdC4JjCMCw" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndEvent" xmi:id="_1N39oKPPEe6PUdC4JjCMCw" name="End2" incoming="_1OBuoKPPEe6PUdC4JjCMCw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_1N5LwaPPEe6PUdC4JjCMCw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_1N5LwKPPEe6PUdC4JjCMCw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_1N5LwqPPEe6PUdC4JjCMCw" name="" content="" returnTypeFixed="true"/>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_w-PUcKPPEe6PUdC4JjCMCw" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_w-PUcaPPEe6PUdC4JjCMCw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_w-PUcqPPEe6PUdC4JjCMCw">
        <targetForm xmi:type="expression:Expression" xmi:id="_w-PUc6PPEe6PUdC4JjCMCw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1OBuoKPPEe6PUdC4JjCMCw" target="_1N39oKPPEe6PUdC4JjCMCw" source="_0tplcKPPEe6PUdC4JjCMCw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1OC8wKPPEe6PUdC4JjCMCw"/>
        <condition xmi:type="expression:Expression" xmi:id="_1OC8waPPEe6PUdC4JjCMCw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <configurations xmi:type="configuration:Configuration" xmi:id="_3RBhIKPPEe6PUdC4JjCMCw" name="Qualification" version="9" username="walter.bates">
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_3RBhIaPPEe6PUdC4JjCMCw" id="CONNECTOR"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_3RCIMKPPEe6PUdC4JjCMCw" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_3RCIMaPPEe6PUdC4JjCMCw" id="OTHER"/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_3REkc6PPEe6PUdC4JjCMCw" name="serverUrl" value="http://localhost:8080/bonita" typeClassname="java.lang.String"/>
      </configurations>
      <configurations xmi:type="configuration:Configuration" xmi:id="_UaD0cBN8Ee-sFtxxgBEFKw" name="presales" version="9" username="walter.bates">
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_UaD0cRN8Ee-sFtxxgBEFKw" id="CONNECTOR"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_UaEbgRN8Ee-sFtxxgBEFKw" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_UaEbghN8Ee-sFtxxgBEFKw" id="OTHER"/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_UaEbiBN8Ee-sFtxxgBEFKw" name="serverUrl" value="http://localhost:8080/bonita" typeClassname="java.lang.String"/>
      </configurations>
      <parameters xmi:type="parameter:Parameter" xmi:id="_29mO0KPPEe6PUdC4JjCMCw" name="serverUrl" typeClassname="java.lang.String"/>
      <contract xmi:type="process:Contract" xmi:id="_w-P7gKPPEe6PUdC4JjCMCw"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_w-M4MKPPEe6PUdC4JjCMCw">
        <name xmi:type="expression:Expression" xmi:id="_w-NfQKPPEe6PUdC4JjCMCw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_w-NfQaPPEe6PUdC4JjCMCw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_w-NfQqPPEe6PUdC4JjCMCw">
        <name xmi:type="expression:Expression" xmi:id="_w-NfQ6PPEe6PUdC4JjCMCw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_w-NfRKPPEe6PUdC4JjCMCw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_w-NfRaPPEe6PUdC4JjCMCw">
        <name xmi:type="expression:Expression" xmi:id="_w-NfRqPPEe6PUdC4JjCMCw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_w-NfR6PPEe6PUdC4JjCMCw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_w-NfSKPPEe6PUdC4JjCMCw">
        <name xmi:type="expression:Expression" xmi:id="_w-NfSaPPEe6PUdC4JjCMCw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_w-NfSqPPEe6PUdC4JjCMCw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_w-NfS6PPEe6PUdC4JjCMCw">
        <name xmi:type="expression:Expression" xmi:id="_w-NfTKPPEe6PUdC4JjCMCw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_w-NfTaPPEe6PUdC4JjCMCw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_rY-p4zz9Ee6gLs_iytuHkw" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_rY-p5Dz9Ee6gLs_iytuHkw" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_rY-p5Tz9Ee6gLs_iytuHkw" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_rY-p5jz9Ee6gLs_iytuHkw" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_rY-p5zz9Ee6gLs_iytuHkw" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_rY-p6Dz9Ee6gLs_iytuHkw" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_rY-p6Tz9Ee6gLs_iytuHkw" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_rY-p6jz9Ee6gLs_iytuHkw" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_rY-p6zz9Ee6gLs_iytuHkw" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_rY-p7Dz9Ee6gLs_iytuHkw" type="Process" element="_rY-CwDz9Ee6gLs_iytuHkw" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_rY-p7Tz9Ee6gLs_iytuHkw" type="2007" element="_rY-CwTz9Ee6gLs_iytuHkw">
      <children xmi:type="notation:DecorationNode" xmi:id="_rY-p7jz9Ee6gLs_iytuHkw" type="5008" element="_rY-CwTz9Ee6gLs_iytuHkw"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_rY-p7zz9Ee6gLs_iytuHkw" type="7001" element="_rY-CwTz9Ee6gLs_iytuHkw">
        <children xmi:type="notation:Node" xmi:id="_rY-p8Dz9Ee6gLs_iytuHkw" type="3007" element="_rY-Cwjz9Ee6gLs_iytuHkw">
          <children xmi:type="notation:DecorationNode" xmi:id="_rY-p8Tz9Ee6gLs_iytuHkw" type="5007" element="_rY-Cwjz9Ee6gLs_iytuHkw"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_rY-p8jz9Ee6gLs_iytuHkw" type="7002" element="_rY-Cwjz9Ee6gLs_iytuHkw">
            <children xmi:type="notation:Shape" xmi:id="_rY-p9jz9Ee6gLs_iytuHkw" type="3002" element="_rY-Cwzz9Ee6gLs_iytuHkw" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_rY-p9zz9Ee6gLs_iytuHkw" type="5024" element="_rY-Cwzz9Ee6gLs_iytuHkw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_rY-p-Dz9Ee6gLs_iytuHkw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rY-p-Tz9Ee6gLs_iytuHkw" x="60" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_xiovsDz9Ee6gLs_iytuHkw" type="3003" element="_xilsYDz9Ee6gLs_iytuHkw" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_xipWwDz9Ee6gLs_iytuHkw" type="5025" element="_xilsYDz9Ee6gLs_iytuHkw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_xipWwTz9Ee6gLs_iytuHkw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xiovsTz9Ee6gLs_iytuHkw" x="277" y="72"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_rY-p-jz9Ee6gLs_iytuHkw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_rY-p-zz9Ee6gLs_iytuHkw" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_rY-p_Dz9Ee6gLs_iytuHkw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_rY-p_Tz9Ee6gLs_iytuHkw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rY-p_jz9Ee6gLs_iytuHkw"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_rY-p_zz9Ee6gLs_iytuHkw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_rY-qADz9Ee6gLs_iytuHkw" fontName=".AppleSystemUIFont"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_rY-qATz9Ee6gLs_iytuHkw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_rY-qAjz9Ee6gLs_iytuHkw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rY-qAzz9Ee6gLs_iytuHkw" width="1080" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_w-_iYKPPEe6PUdC4JjCMCw" type="2007" element="_w7zEcKPPEe6PUdC4JjCMCw">
      <children xmi:type="notation:DecorationNode" xmi:id="_w_DMwKPPEe6PUdC4JjCMCw" type="5008" element="_w7zEcKPPEe6PUdC4JjCMCw"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_w_DMwaPPEe6PUdC4JjCMCw" type="7001" element="_w7zEcKPPEe6PUdC4JjCMCw">
        <children xmi:type="notation:Shape" xmi:id="_0t0kkKPPEe6PUdC4JjCMCw" type="3002" element="_0tplcKPPEe6PUdC4JjCMCw" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_0t3A0KPPEe6PUdC4JjCMCw" type="5024" element="_0tplcKPPEe6PUdC4JjCMCw">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_0t3n4KPPEe6PUdC4JjCMCw" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0t1LoKPPEe6PUdC4JjCMCw" x="104" y="98"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_1N8PEKPPEe6PUdC4JjCMCw" type="3003" element="_1N39oKPPEe6PUdC4JjCMCw" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_1N82IKPPEe6PUdC4JjCMCw" type="5025" element="_1N39oKPPEe6PUdC4JjCMCw">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_1N82IaPPEe6PUdC4JjCMCw" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1N8PEaPPEe6PUdC4JjCMCw" x="289" y="104"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_w_AJcKPPEe6PUdC4JjCMCw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_w_AJcaPPEe6PUdC4JjCMCw" fontName=".AppleSystemUIFont"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_w_AJcqPPEe6PUdC4JjCMCw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_w_DMwqPPEe6PUdC4JjCMCw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_w_AJc6PPEe6PUdC4JjCMCw" width="1320" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_rY-qBDz9Ee6gLs_iytuHkw"/>
    <edges xmi:type="notation:Connector" xmi:id="_xitoMDz9Ee6gLs_iytuHkw" type="4001" element="_xitBIDz9Ee6gLs_iytuHkw" source="_rY-p9jz9Ee6gLs_iytuHkw" target="_xiovsDz9Ee6gLs_iytuHkw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xitoMzz9Ee6gLs_iytuHkw" type="6001" element="_xitBIDz9Ee6gLs_iytuHkw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xitoNDz9Ee6gLs_iytuHkw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xitoMTz9Ee6gLs_iytuHkw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xitoMjz9Ee6gLs_iytuHkw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1OGnIKPPEe6PUdC4JjCMCw" type="4001" element="_1OBuoKPPEe6PUdC4JjCMCw" source="_0t0kkKPPEe6PUdC4JjCMCw" target="_1N8PEKPPEe6PUdC4JjCMCw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1OHOMKPPEe6PUdC4JjCMCw" type="6001" element="_1OBuoKPPEe6PUdC4JjCMCw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1OHOMaPPEe6PUdC4JjCMCw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1OGnIaPPEe6PUdC4JjCMCw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1OGnIqPPEe6PUdC4JjCMCw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
