== Migration notes (January 23, 2025 at 5:30:05 PM CET)

=== Updates

* Bonita project parent has been updated from `10.0.0` to `10.2.1`.
* Bonita Reporting Application version updated to `2.0.0`. This is the minimal compatible version with Bonita 2024.3 and above.

== Migration notes (May 16, 2024 at 11:35:25 AM CEST)

=== Updates

* Bonita project parent has been updated from `9.0.3` to `10.0.0`.
* Required Java version updated to `17`. Make sure that your third party dependencies are compliant with Java 17.

== Migration notes (December 19, 2023 at 1:45:31 PM CET)

=== Additions

* Bonita Admin Application has been added in the project extensions.
* `javax.persistence:javax.persistence-api` provided dependency has been added to the BDM dao-client module.

=== Updates

* `.gitignore` file has been updated.
* `app/.gitignore` file has been updated.
* This project now depends on the Bonita project parent pom. This parent pom configures all the required plugins and dependencies versions for a given Bonita version.
* Rest API Extensions and Themes projects have been moved in the project layout to benefit from the Maven multi module approach. It means that files location inside the project have changed.  It is a technical change and will not impact the design usage in Bonita Studio.New maven modules and their respective `pom.xml` files are *reserved for internal Studio use*.
* Project's extensions are now build in their own maven module. While it does not impact the design usage, this internal change allow the usage of a standard Maven build lifecycle.  All extensions share the same `version` and `groupId` of the parent project. It is enforced by the format of the Bonita project and must not be changed.
* Application module build configuration has been updated to support Maven build.
* Bdm model module build configuration has been updated to support Maven build.

=== Removals

* `maven.compiler.release` property has been removed from parent pom. This property is now inherited from the Bonita Project parent pom.
* `maven-install-plugin.version` property has been removed from parent pom. This property is now inherited from the Bonita Project parent pom.
* `maven-jar-plugin.version` property has been removed from parent pom. This property is now inherited from the Bonita Project parent pom.
* `maven-source-plugin.version` property has been removed from parent pom. This property is now inherited from the Bonita Project parent pom.
* `bonita-project-maven-plugin.version` property has been removed from parent pom. This property is now inherited from the Bonita Project parent pom.
* `maven-shade-plugin.version` property has been removed from parent pom. This property is now inherited from the Bonita Project parent pom.
* `maven-compiler-plugin.version` property has been removed from parent pom. This property is now inherited from the Bonita Project parent pom.
* `build-helper-maven-plugin.version` property has been removed from parent pom. This property is now inherited from the Bonita Project parent pom.
* `maven-clean-plugin.version` property has been removed from parent pom. This property is now inherited from the Bonita Project parent pom.
* `project.reporting.outputEncoding` property has been removed from parent pom. This property is now inherited from the Bonita Project parent pom.
* `flatten-maven-plugin.version` property has been removed from parent pom. This property is now inherited from the Bonita Project parent pom.
* `bonita.runtime.version` property has been removed from parent pom. This property is now inherited from the Bonita Project parent pom.
* `project.build.sourceEncoding` property has been removed from parent pom. This property is now inherited from the Bonita Project parent pom.
* `maven-resources-plugin.version` property has been removed from parent pom. This property is now inherited from the Bonita Project parent pom.
* `maven-deploy-plugin.version` property has been removed from parent pom. This property is now inherited from the Bonita Project parent pom.
* `org.bonitasoft.runtime:bonita-runtime-bom` BOM has been removed from parent pom. This BOM is now inherited from the Bonita Project parent pom.
* `org.apache.maven.plugins:maven-install-plugin` plugin has been removed from parent pom. Its configuration is now inherited from the Bonita Project parent pom.
* `org.apache.maven.plugins:maven-source-plugin` plugin has been removed from parent pom. Its configuration is now inherited from the Bonita Project parent pom.
* `org.apache.maven.plugins:maven-compiler-plugin` plugin has been removed from parent pom. Its configuration is now inherited from the Bonita Project parent pom.
* `org.apache.maven.plugins:maven-clean-plugin` plugin has been removed from parent pom. Its configuration is now inherited from the Bonita Project parent pom.
* `org.apache.maven.plugins:maven-jar-plugin` plugin has been removed from parent pom. Its configuration is now inherited from the Bonita Project parent pom.
* `org.apache.maven.plugins:maven-resources-plugin` plugin has been removed from parent pom. Its configuration is now inherited from the Bonita Project parent pom.
* `org.apache.maven.plugins:maven-deploy-plugin` plugin has been removed from parent pom. Its configuration is now inherited from the Bonita Project parent pom.
* `org.apache.maven.plugins:maven-shade-plugin` plugin has been removed from parent pom. Its configuration is now inherited from the Bonita Project parent pom.
* `org.codehaus.mojo:flatten-maven-plugin` plugin has been removed from parent pom. Its configuration is now inherited from the Bonita Project parent pom.
* `org.bonitasoft.maven:bonita-project-maven-plugin` plugin has been removed from parent pom. Its configuration is now inherited from the Bonita Project parent pom.
* `org.codehaus.mojo:build-helper-maven-plugin` plugin has been removed from parent pom. Its configuration is now inherited from the Bonita Project parent pom.
* Deprecated provided groovy classes `BonitaUsers`, `BonitaSql`, `BonitaXML` and `BonitaTypes` have been removed.
* The `flatten-maven-plugin` executions have been removed from the Bdm parent module. They are now inherited from the Bonita project parent.

== Migration notes (August 11, 2023 at 5:51:53 PM CEST)

=== Updates

* `bonita.runtime.version` has been updated from `7.15.1` to `8.0.0`.
* `bonita-project-maven-plugin.version` has been updated from `0.0.6` to `0.1.0`.
* `com.company.model:bdm-client:jar:1.0.0` dependency has been replaced with `${project.groupId}:presales-bpm-template-bdm-model:jar:${project.version}`.
* The project layout has been changed in favor of a multi modules maven project. It means that files location inside the project have changed.  It is a technical change and will not impact the design usage in Bonita Studio.New maven modules and their respective `pom.xml` files are *reserved for internal Studio use*.
* Project's Business Data Model is now build in its own maven module. While it does not impact the design usage, it can now be built and deployed independently from a Studio.  The BDM model dependency share the same `version` and `groupId` of the parent project. It is enforced by the format of the Bonita project and must not be changed.
* `default_profile.xml` profile xml schema version has been updated.

== Migration notes (October 10, 2022 at 11:12:06 AM CEST)

=== Updates

* `bonita.runtime.version` has been updated from `7.13.1` to `7.15.0`.
* `bonita-project-maven-plugin.version` has been updated from `0.0.4` to `0.0.6`.

== Migration notes (December 7, 2021 at 10:22:48 AM CET)

=== Updates

* `bonita-project-maven-plugin.version` has been updated from `0.0.3` to `0.0.4`.

== Migration notes (November 2, 2021 at 3:18:21 PM CET)

=== Additions

* Bonita projects are now Maven projects and rely on the https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html[Maven dependency mechanism] to manage their dependencies. Check the documentation for more information about https://www.bonitasoft.com/bos_redirect.php?bos_redirect_id=727&bos_redirect_major_version=7.13&bos_redirect_minor_version=0&bos_redirect_product=bos[Project composition].

=== Updates

* Groovy version has been updated from `2.4.x` to `3.0.x`
* Only Java `11` version is now supported. This might impact your existing projet if you were still using Java 8. Some dependencies in your project might be incompatible with the _Java Platform Module System_ introduced in Java 9.

=== Removals

* `lib` folder and its content has been removed.

