name: build
on:
  push:
    branches:
      - develop
      - master
      - main
  pull_request:
    branches:
      - develop
      - master
      - main
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre_requisites:
    uses: bonitasoft-presales/presales_workflows/.github/workflows/reusable_prerequisites.yml@v1.6.0
    secrets: inherit

  create_server:
    uses: bonitasoft-presales/presales_workflows/.github/workflows/reusable_create_server.yml@v1.6.0
    secrets: inherit

  set_bonita_dns:
    runs-on: ubuntu-latest
    needs:
      - create_server
    outputs:
      publicDnsName: ${{ steps.read-yaml-file.outputs['publicDnsName'] }}
    steps:
      - name: Download artifact instance.yaml file
        uses: actions/download-artifact@v4
        with:
          name: aws_instance

      - name: read-yaml-file
        uses: pietrobolcato/action-read-yaml@1.1.0
        id: read-yaml-file
        with:
          config: ${{ github.workspace }}/aws_instance.yaml

      #      - name: set AWS_PUBLIC_DNS_HOSTNAME env variable
      #        id: set-env-variable
      #        run: |
      #          echo "AWS_PUBLIC_DNS_HOSTNAME=${{ steps.read-yaml-file.outputs['publicDnsName'] }}" >> $GITHUB_ENV

      - name: display AWS_PUBLIC_DNS_HOSTNAME result
        id: display-env-variable
        run: |
          echo "publicDnsName : ${{ steps.read-yaml-file.outputs['publicDnsName'] }}" 

  build_sca:
    needs:
      - create_server
      - set_bonita_dns
    uses: bonitasoft-presales/presales_workflows/.github/workflows/reusable_build_sca.yml@v1.6.0
    secrets: inherit

  deploy_SCA:
    needs:
      - create_server
      - set_bonita_dns
      - build_sca
    uses: bonitasoft-presales/presales_workflows/.github/workflows/reusable_deploy_sca.yml@v1.6.0
    secrets:
      licence_base64: ${{ secrets.LICENSE_V10_3_BASE_64 }}
      AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
      AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECURITY_GROUP_ID: ${{ secrets.AWS_SECURITY_GROUP_ID }}
      AWS_SSH_USER: ${{ secrets.AWS_SSH_USER }}
      JFROG_USER: ${{ secrets.JFROG_USER }}
      JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
      GHP_USER: ${{ secrets.GHP_USER }}
      GHP_TOKEN: ${{ secrets.GHP_TOKEN }}
      HEALTHZ_USERNAME: ${{ secrets.HEALTHZ_USERNAME }}
      HEALTHZ_PASSWORD: ${{ secrets.HEALTHZ_PASSWORD }}

  deploy_UIB:
    needs:
      - create_server
      - set_bonita_dns
      - deploy_SCA
    uses: bonitasoft-presales/presales_workflows/.github/workflows/reusable_deploy_uib_aws.yml@v1.6.0
    with:
      bonita_dns_name: ${{ needs.set_bonita_dns.outputs.publicDnsName }}
    secrets: inherit

  run-IT:
    needs:
      - pre_requisites
      - deploy_SCA
      - deploy_UIB
      - create_server
    uses: bonitasoft-presales/presales_workflows/.github/workflows/reusable_run_it.yml@v1.6.0
    secrets: inherit

  run-Datagen:
    needs:
      - pre_requisites
      - run-IT
    uses: bonitasoft-presales/presales_workflows/.github/workflows/reusable_run_datagen.yml@v1.6.0
    secrets: inherit
